m_min: 1
m_max: 16
n_m: 3
waymark_type: 'linear'

d_min: 8
d_max: 128
n_d: 4

n: 50000
dtype: 'float'

optimizer:
  lr: 1e-3
  n_steps: 10000
  val_frac: 0

hydra:
  run:
    dir: ./hydra_outputs/${nowpt:%m-%d-%Y}/${nowpt:%H-%M}

